### ISSUE TITLE
Format Document states unknown formatter

### ISSUE THREAD

**Issue by nmccready** [raynigon/vscode-nginx-formatter#7] opened 2019-11-12 13:26 UTC
![Screen Shot 2019-11-12 at 8 26 10 AM](https://user-images.githubusercontent.com/583593/68675542-1a845e00-0526-11ea-8e5c-ba012aeb7837.png)

The formatter is installed.

**Comment by dotview** [comment] 2019-11-14 06:34
same issue

**Comment by ConradKurth** [comment] 2019-11-21 22:37
So i actually just figured this out, you need to add 

```json
"files.associations": {
        "nginx.conf": "nginx"
}
```

to your settings config

**Comment by esamattis** [comment] 2019-12-13 11:53
I had prettier colliding with this.

Fix:

```json
"[nginx]": {
    "editor.defaultFormatter": "raynigon.nginx-formatter"
}
```

**Comment by raynigon** [comment] 2019-12-28 13:49
Hey together,
sorry for the late answer.
There were some breaking changes in the extension api.
Fixed it with version v0.0.7 and submitted the version to the marketplace.

**Comment by iulo** [comment] 2020-04-13 08:10
@raynigon still get the bug with 0.0.8

**Comment by brendan-mccoy** [comment] 2021-04-17 00:39
I'm also getting it, even with 
```
"[nginx]": {
    "editor.defaultFormatter": "raynigon.nginx-formatter"
}
```

**Comment by raynigon** [comment] 2021-04-17 05:29
Hi @brendan-mccoy ,

let me take a look. Can you please add a list of all your installed Plugins? I think there is some side effect between multiple Plugins :/

**Comment by brendan-mccoy** [comment] 2021-05-04 00:11
At the time I was getting it with this plugin and the prereq, plus the Remote Developer tools pack, docker, and powershell. However, it seems to have randomly stopped. I can't really say why? Certain files would work and others not, even when doing a Format With Nginx. So at least my comment can be considered noise unless I determine a specific cause for my instance.

**Comment by raynigon** [comment] 2021-08-13 12:05
Unable to dertmine the cause, therefore closing this with resolution `cant fix`

**Closed** 2021-08-13 12:04 UTC

**Comment by justrealmilk** [comment] 2021-09-20 18:26
From Prettier
```
["INFO" - 4:25:12 AM] Forced formatting will not use ignore files.
["INFO" - 4:25:12 AM] Formatting c:\Users\Tom\AppData\Local\Temp\fz3temp-2\file
["INFO" - 4:25:12 AM] File Info:
{
  "ignored": false,
  "inferredParser": null
}
["WARN" - 4:25:12 AM] Parser not inferred, trying VS Code language.
["ERROR" - 4:25:12 AM] Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser.
```

**Comment by raynigon** [comment] 2021-09-20 18:44
@justrealmilk could you please provide more Information

**Comment by justrealmilk** [comment] 2021-09-20 18:46
> @justrealmilk could you please provide more Information

As per the original issue, VS Code says there's no formatter installed when you attempt to Format Document. When you use the force option, Prettier supplies an error log which I posted. Perhaps it's not compatible with Prettier?
